import Head from 'next/head'
import { useState } from 'react';
import { Alert, Layout, Button, Form, Input, Typography } from 'antd'
import styles from '../styles/Home.module.css'

const { Header, Content, Footer } = Layout;
const { Title } = Typography;

export default function Home() {
  const [status, setStatus] = useState<'initial' | 'error' > ('initial');
  const [form] = Form.useForm();
  const [message, setMessage] = useState('')

  const urlValidation = () => {
    setStatus('error');
    const error = form.getFieldError('link').join('')
    setMessage(error)
  }

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <div className={styles.logo} />
      </Header>
      <Content className={styles.content}>
        <div className={styles.shortener}> 
          <Title level={5}> Copy &amp; Paste your length link</Title>
          <Form onFinishFailed={urlValidation} form={form}>
            <div className={styles.linkField}>
              <div className={styles.linkFieldInput}>
                <Form.Item name="link" noStyle rules={[{
                  required: true,
                  message: 'Please paste a correct link',
                  type: 'url'
                }]}>
                  <Input placeholder="https://my-super-long-link.com" size="large" type="link"/>
                </Form.Item>
              </div>

              <div className={styles.linkFieldButton}>
                <Form.Item>
                  <Button type="primary" htmlType="submit" style={{ width: '100%'}} size="large">
                    Shorten
                  </Button>
                </Form.Item>
              </div>
          </div>
        </Form>
        {status === 'error' && <Alert showIcon message={message} type="error" /> }
        </div>
      </Content>

      <Footer className={styles.footer}>
        This is my footer @ 2021
      </Footer>
    </Layout>
  )
}
