import Head from 'next/head'
import { Layout, Button, Form, Input } from 'antd'
import styles from '../styles/Home.module.css'

const { Header, Content, Footer } = Layout;

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <div className={styles.logo} />
      </Header>
      <Content className={styles.content}>
        <div className={styles.shortener}> 
          <Form>
            <div className={styles.linkField}>
              <div className={styles.linkFieldInput}>
                <Form.Item name="link" rules={[]}>
                  <Input placeholder="https://my-super-long-link.com" size="large"/>
                </Form.Item>
              </div>

              <div className={styles.linkFieldButton}>
                <Form.Item>
                  <Button type="primary" htmlType="submit" style={{ width: '100%'}} size="large">
                    Shorten
                  </Button>
                </Form.Item>
              </div>
          </div>
        </Form>
        </div>
      </Content>

      <Footer className={styles.footer}>
        This is my footer @ 2021
      </Footer>
    </Layout>
  )
}
