import Head from 'next/head'
import { Layout } from 'antd'
import styles from '../styles/Home.module.css'

const { Header, Content, Footer } = Layout;

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <div className={styles.logo} />
      </Header>
      <Content className={styles.content}>
        <h1> Hello World!</h1>
      </Content>
      <Footer className={styles.footer}>
         This is my footer @ 2021
      </Footer>
    </Layout>
  )
}
